spring:
  application:
    name: club-service
  datasource:
    url: jdbc:mysql://localhost:3306/club
    username: root
    password: OMKARm*@46!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # ADD THIS KAFKA SECTION
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # This sends plain JSON without Java type headers to prevent errors
        spring.json.add.type.headers: false


server:
  port: 8082

USER_SERVICE_URL: http://localhost:8081
CLUB_SERVICE_URL: http://localhost:8082
EVENT_SERVICE_URL: http://localhost:8083
NOTIFICATION_SERVICE_URL: http://localhost:8085