spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: OMKARm*@46!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:connectedu8@gmail.com}
    password: ${MAIL_PASSWORD:kcjo fimn twjh mlvk}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # --- KAFKA CONFIGURATION SECTION ---
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
#      # Re-introducing the error handler to gracefully skip bad messages
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        # Tell the error handler which actual deserializers to use
#        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        # Trust all packages to prevent any future class name issues
#        spring.json.trusted.packages: "*"
#        # --- ADD THIS LINE ---
#        # This tells the consumer what object to create when no type info is in the message header.
#        # Use the class name *as it exists in this service*.
#        spring.json.value.default.type: com.campusconnect.notificationservice.dto.CertificateNotificationRequest
#        # ADD THIS FOR THE NEW TOPIC
#        spring.json.type.mapping: userRegistered:com.campusconnect.notificationservice.dto.UserRegisteredRequest

server:
  port: 8085

notify:
  default-from: no-reply@campusconnect.example.com

USER_SERVICE_URL: http://localhost:8081
CLUB_SERVICE_URL: http://localhost:8082
EVENT_SERVICE_URL: http://localhost:8083