spring:
  application:
    name: certificate-service

  datasource:
    url: jdbc:mysql://localhost:3306/certificate
    username: root
    password: OMKARm*@46!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # Correctly indented properties block
      properties:
        # Prevents sending the class name in message headers, fixing the error
        spring.json.add.type.headers: false

eureka:
  instance:
    prefer-ip-address: true # Add this line
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8086

USER_SERVICE_URL: http://localhost:8081
EVENT_SERVICE_URL: http://localhost:8083
NOTIFICATION_SERVICE_URL: http://localhost:8085


# ===== ADD THIS AWS CONFIGURATION SECTION =====
aws:
  region: ap-south-1 # The region you created your bucket in
  s3:
    bucket-name: connectedu-media # Your S3 bucket name
  credentials:
    access-key: AKIAYQYUBDK4RVKIGINE # Your AWS Access Key
    secret-key: ZrcjKG0eg8KDNMveZ3ngChfT2Yqh6IrKSmpOH4hQ # Your AWS Secret Key