package com.connectedu.chat.engine;

public enum Intent {
    GREETING,
    GET_UPCOMING_EVENTS,
    GET_PAST_EVENTS,
    GET_ALL_CLUBS,
    GET_CONTACT_INFO,
    GET_CLUB_SPECIFIC_EVENTS,
    SEARCH_EVENTS_BY_YEAR,
    GET_SPECIFIC_CONTACT_INFO,
    GET_MY_REGISTRATIONS,
    SEARCH_SPECIFIC_EVENT,
    UNKNOWN
}