server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**, /api/users/**, /internal/api/users/**


        - id: upload-service
          uri: lb://discussion-service
          predicates:
              - Path=/api/uploads/**


        - id: discussion-service
          uri: lb://discussion-service
          predicates:
            - Path=/api/clubs/{clubId}/events/{eventId}/discussions/**


        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/clubs/{clubId}/events/**, /internal/api/events/**, /api/events/upcoming, /api/events/my-registrations


        - id: club-service
          uri: lb://club-service
          predicates:
            - Path=/api/clubs/**, /internal/api/clubs/**


        - id: certificate-service
          uri: lb://certificate-service
          predicates:
            - Path=/api/certificates/**


        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**