spring:
  application:
    name: discussion-service
  datasource:
    url: jdbc:mysql://localhost:3306/discussion
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8084

USER_SERVICE_URL: http://localhost:8081
CLUB_SERVICE_URL: http://localhost:8082
EVENT_SERVICE_URL: http://localhost:8083
NOTIFICATION_SERVICE_URL: http://localhost:8085

aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET}
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}