server:
  port: 8088 # Choose an unused port

spring:
  application:
    name: payment-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  instance:
    prefer-ip-address: true # Add this line
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# --- Razorpay Configuration ---
razorpay:
  key-id: rzp_test_RVPphcJHGKgmdz
  key-secret: LqTpKsomnIV37Z6MrmtyCHcW