spring:
  application:
    name: event-service
  datasource:
    url: jdbc:mysql://localhost:3306/event
    username: root
    password: OMKARm*@46!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # --- CORRECTED INDENTATION ---
  # The 'kafka:' block must be at the same level as 'jpa:' and 'datasource:'
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # This sends plain JSON without Java type headers to prevent errors
        spring.json.add.type.headers: false



application:
  security:
    jwt:
      # PASTE THE EXACT SAME SECRET KEY FROM YOUR OTHER SERVICES
      secret-key: NjdFNkEzRDA3RTY4NkM1OUQxN0E5RkU4NzQ2Njg5QzI3MjgzNTZFRDE3RTFCOTE1RkY1NEZDRTE1NTYyN0IzNA==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

USER_SERVICE_URL: http://localhost:8081
CLUB_SERVICE_URL: http://localhost:8082
EVENT_SERVICE_URL: http://localhost:8083
NOTIFICATION_SERVICE_URL: http://localhost:8085
CERTIFICATE_SERVICE_URL: http://localhost:8086